name: signals_lint
description: linter and developer tool for signals
version: 6.0.0
repository: https://github.com/rodydavis/signals.dart
homepage: https://dartsignals.dev/
documentation: https://dartsignals.dev/
topics:
  - state-management
  - state
  - signals
  - rx
  - linter

environment:
  sdk: ^3.0.0

dependencies:
  analyzer: ^8.1.1
  analyzer_plugin: ^0.13.7
  collection: ^1.17.2
  custom_lint_builder: ^0.8.1

dev_dependencies:
  lints: ^6.0.0
  test: ^1.24.9
  signals: ^6.0.2
